application: retro-maker
version: 1
runtime: python
api_version: 1

handlers:
- url: /cron/.*
  script: cron.py
  login: admin
- url: /task/.*
  script: taskqueue.py
  login: admin
- url: /.*
  script: app.py
